baseURL: "https://arrrrrmin.netlify.app"
title: "arrrrrmin.netlify.app - writing about development, data science, aws"
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

menu:
    main:
        - name: posts
          url: posts/
          weight: 5
        - name: portfolio
          url: portfolio
          weight: 10
        - name: search
          url: search
          weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON
            
googleAnalytics: ""

minify:
    disableXML: true
    minifyOutput: true
    
params:
    env: production # to enable opengraph, twitter-cards and schema.
    title: "arrrrrmin.netlify.app"
    description: "Writing about development, data science, aws"
    author: "arrrrrmin"

    images: "https://avatars3.githubusercontent.com/u/43553423?s=460&u=c4705accaaa6caf3ddcc188117a58fc5173a8e6b&v=4"

    ShowReadingTime: true
    ShowShareButtons: false
    ShowToc: true
    TocOpen: true
    hideSummary: false
    hidemeta: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    comments: false
    ShowPostNavLinks: true
    defaultTheme: light
    disableThemeToggle: false
    disableSpecial1stPost: true
    editPost:
      URL: "https://github.com/arrrrrmin/arrrrrmin.netlify.com/blob/main/content/"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link
    
    # fuseOpts:
    #   isCaseSensitive: false
    #   shouldSort: true
    #   location: 0
    #   distance: 1000
    #   threshold: 0.4
    #   minMatchCharLength: 0
    #   keys: ["title", "permalink", "summary", "content"] ##  can be less but not more than shown in list
    
    # assets:
    #     favicon: "static/favicon.ico"
    #     favicon16x16: "static/favicon16x16.png"
    #     favicon32x32: "static/favicon32x32.png"
    #     apple_touch_icon: "static/apple_touch_icon.png"
    #     safari_pinned_tab: "static/apple_touch_icon.png"

    label:
        text: "Home"
        icon: "" # "/apple-touch-icon.png"
        iconHeight: 60

    # profile-mode
    profileMode:
        enabled: false
        title: "arrrrrmin.netlify.app" # optional default will be site title
        imageUrl: "https://pbs.twimg.com/profile_images/1545306587836960768/2hbCpjgh_400x400.jpg"  # optional
        imageTitle: "UserImage" # optional
        imageWidth: 150 # custom size
        imageHeight: 150 # custom size
        buttons:
        - name: posts
          url: "/posts/"
        - name: portfolio
          url: "/portfolio"
        - name: search
          url: "/search"

    # home-info mode
    homeInfoParams:
        Title: "arrrrrmins personal website"
        Content: ""
        imageUrl: "https://pbs.twimg.com/profile_images/1545306587836960768/2hbCpjgh_400x400.jpg"  # optional

    socialIcons:
        - name: github
          url: "https://github.com/arrrrrmin"
        - name: twitter
          url: "https://twitter.com/arrrrrmin"
        - name: linkedin
          url: "https://www.linkedin.com/in/armin-müller-von-fischer-7581a8165/"

    analytics:
        google:
            SiteVerificationTag: ""
