baseURL = "http://arrrrrmin.netlify.app/"
languageCode = "en-us"
title = "Hi. I'm Armin :)"
theme = "hugo-papermod"
description = "This is my minimalistic freelancer blog-like portfolio"
min_version = "0.74.3"

[author]
  name = "arrrrrmin"
  homepage = "https://github.com/arrrrrmin"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/arrrrrmin"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/arrrrrmin/"

[[menu.main]]
name = "Intro"
url = "/posts/intro"
weight = 1

[[menu.main]]
name = "Skills"
url = "/posts/skills"
weight = 1

[[menu.main]]
name = "Projects"
url = "/posts/projects"
weight = 1

[[menu.main]]
name = "Work_Experience"
url = "/posts/work_experience"
weight = 1

