baseURL: "https://arrrrrmin.netlify.app"
title: "hi i'm armin"
paginate: 10
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: ""

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "freelancer portfolio"
    description: "I'm armin. Welcome to my freelancer portfolio."
    author: "arrrrrmin"

    images: "https://avatars3.githubusercontent.com/u/43553423?s=460&u=c4705accaaa6caf3ddcc188117a58fc5173a8e6b&v=4"

    ShowReadingTime: true
    ShowShareButtons: false
    comments: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false

    # assets:
    #     favicon: "static/favicon.ico"
    #     favicon16x16: "static/favicon16x16.png"
    #     favicon32x32: "static/favicon32x32.png"
    #     apple_touch_icon: "static/apple_touch_icon.png"
    #     safari_pinned_tab: "static/apple_touch_icon.png"

    label:
        text: "Home"
        icon: "https://avatars3.githubusercontent.com/u/43553423?s=460&u=c4705accaaa6caf3ddcc188117a58fc5173a8e6b&v=4" # "/apple-touch-icon.png"
        iconHeight: 60

    # profile-mode
    profileMode:
        enabled: false
        title: "<Title>" # optional default will be site title
        imageUrl: "https://avatars3.githubusercontent.com/u/43553423?s=460&u=c4705accaaa6caf3ddcc188117a58fc5173a8e6b&v=4" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/"
        socialIcons: # optional
            - name: "Twitter"
              url: "https://twitter.com/arrrrrmin"
            - name: "Linkedin"
              url: "https://www.linkedin.com/in/armin-müller-von-fischer-7581a8165/"

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B "
        Content: "I'm armin, a freelancing data scientist this is my portfolio"

    socialIcons:
        - name: twitter
          url: "https://twitter.com/arrrrrmin"
        - name: github
          url: "https://github.com/arrrrrmin"
        - name: linkedin
          url: "https://www.linkedin.com/in/armin-müller-von-fischer-7581a8165/"

    analytics:
        google:
            SiteVerificationTag: ""
