@startuml
!theme plain
autonumber

actor User
participant CloudFront
participant Lambda@Edge
participant Cognito
participant S3Bucket

User -> CloudFront: HTTP GET /index.html JWT Auth-Bearer
CloudFront -> Lambda@Edge: Run auth lambda
Lambda@Edge -> Cognito: Validate token
note right of Lambda@Edge
Lambda function can include
additional checks, using users
decoded sub data
end note
Cognito --> Lambda@Edge: <200 Ok>
Lambda@Edge --> CloudFront: <200 Ok>
CloudFront --> S3Bucket: Grant access to Resource
@enduml